version: '2'
services:
  echo:
    build: ./echo
    restart: always
    #ports:
        # - "5000:5000"
    volumes:
     - .:/echo/code
    depends_on:
     - rabbitmq
  rabbitmq:
    image: "rabbitmq"
